- src/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
- src/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardService.java
- src/org/pentaho/platform/dataaccess/datasource/api/DatasourceService.java
- src/org/pentaho/platform/dataaccess/datasource/api/MetadataService.java
- src/org/pentaho/platform/dataaccess/datasource/api/resources/AnalysisResource.java
- src/org/pentaho/platform/dataaccess/datasource/api/resources/DataSourceWizardResource.java
- src/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataResource.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/AnalysisDatasourceService.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/MetadataDatasourceService.java
- test-src/org/pentaho/platform/dataaccess/datasource/DataSourcePublishACLTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardServiceTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/MetadataServiceTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/resources/AnalysisResourceTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/resources/DataSourceWizardResourceTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/resources/JdbcDatasourceResourceTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataResourceTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/resources/ResourceUtilTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DatasourceResourceTest.java
- test-src/solutionACL/system/repository-test-override.spring.xml
adopt the code to new pentaho-platform approach, clean cache for metadata
fix metadata service - return 401 status if user doesn't have permissions and ds does not exist, unit-test for this
fix unit-tests
@pentaho-nbaker please review
> [BACKLOG-1561] - Add the ability to get security/ACL information about a datasource

- src/org/pentaho/platform/dataaccess/datasource/wizard/EmbeddedWizard.java
[BISERVER-12335] - Regression: PUC Datasource Wizard - After New datasource creation Source Type is not returned to default
> [BISERVER-12335] - Regression: PUC Datasource Wizard - After New datasource creation Source Type is not returned to default

- src/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel.xul
Fix verified for IE, FF, Chrome and Safari on Mac.
> [BACKLOG-3535]: The last dialog (data source wizard summary) unable to access the option to "customize" the model.

- src/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java
- test-src/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvModelServiceTest.java
Problem:
By default for numeric fields we set length=0. So we can have ColumnInfo with precision>0 but length=0.
Such combination leads to problem at definition of suitable database type in MSSQLServerDatabaseMeta.getFieldDefinition.
Fix:
Set up default length for numeric fields with precision>0 as length of meta of adviced result.
> [BISERVER-12153]: DSW defaults for zero length for numeric fields in CSV datasource

- ivy.xml
Updated the poi dependency and required 3rd party dependencies.
@pentaho-nbaker @mbatchelor Let's discuss this before including ...
NOTE: there are other pull requests that all must go together
NOTE2: data-access doesn't actually depent on poi so the dependency was removed (it is still coming in transitively)
> [PRD-5459] Upgraded poi to version 3.12

- src/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
- src/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardService.java
- src/org/pentaho/platform/dataaccess/datasource/api/DatasourceService.java
- src/org/pentaho/platform/dataaccess/datasource/api/MetadataService.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardServiceTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/MetadataServiceTest.java
Comment from QA(Pavel Hrakovich):
During verification of BISERVER-12446 with biserver-ee-6.0-Nightly (138) I encountered the following system behavior:
Case 1
Non-admin user with “Manage data sources” and “Create content” permissions can delete any custom connections (JDBC) but cannot delete Data Sources (Analysis, MetaData, Data Source Wizard).
Case 2
Non-admin user with “Manage data sources” and “Create content” permissions cannot delete default connections (Audit, pentaho_operation_mart, SampleData). Default admin-user also cannot delete such connections.
Fix for Case 1 added. As for Case 2, this will break referential integrity, so as for me right now it's works correctly.
@rmansoor @pminutillo @mdamour1976 
Can you please review it and give your opinion about Case 2?
> BISERVER-12446 - Unable to delete Data Source Connection: additional pull-request

- src/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages.properties
- test-src/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java
Cherry-pick of https://github.com/pentaho/data-access/pull/689
@rmansoor 
Please review.
> SP-2394 - Backport of BISERVER-12815 - Manage Data Sources: User can import an .xmi using "Import Analysis" (6.0 Suite)

- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImpl.java
- test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java
- When deleting logical model, delete it's both (reporting and analysis) representations.
- Delete domain if it has no logical models.
@mdamour1976, @e-cuellar, review it please.
> [BISERVER-12392] Data Source is not removed completely if it is deleted from PIR/PA "Select Data Source" wizard page

- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImpl.java
- test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java
- When deleting logical model, delete it's both (reporting and analysis) representations.
- Delete domain if it has no logical models.
- Tests written.
- Checkstyle applied.
@mdamour1976, review it please, this is a backport of https://github.com/pentaho/data-access/pull/690
> [SP-2410] Backport of BISERVER-12392 - Data Source is not removed completely if it is deleted from PIR/PA "Select Data Source" wizard page (6.0 Suite)

- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImpl.java
- test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java
- When deleting logical model, delete it's both (reporting and analysis) representations.
- Delete domain if it has no logical models.
- Tests written.
- Checkstyle applied.
@mdamour1976, review it please, this is a backport of #690
> [SP-2411] Backport of BISERVER-12392 - Data Source is not removed completely if it is deleted from PIR/PA "Select Data Source" wizard page (5.4 Suite)

- src/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java
Backport of https://github.com/pentaho/data-access/pull/691
@rmansoor @pamval 
Please review.
> SP-2442 - Backport of BISERVER-12233 - Exported Mondrian schemas when exported from DAW are exported as schema.xml (5.4 Suite)

- src/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
- test-src/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java
Cherry-pick of https://github.com/pentaho/data-access/pull/691
@rmansoor @pamval 
Please review.
> SP-2441 - Backport of BISERVER-12233 - Exported Mondrian schemas when exported from DAW are exported as schema.xml (6.0 Suite)

- src/org/pentaho/platform/dataaccess/datasource/wizard/GwtDatasourceEditorEntryPoint.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/controllers/ConnectionController.java
Added a way to override the behavior of relying on a selected connection in the DSW dialog and all of it's binding (because you never see it in this repro path and was causing the bug).  So I allow the setting of the connection to use in the edit connection dialog.
> [ANALYZER-3243] - Error to Edit JDBC connection

- src/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages.properties
- test-src/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java
reverting commits dd72b841c10965efa5c2923c6ca851aeb6bd4052 and dd72b841c10965efa5c2923c6ca851aeb6bd4052 which were done for BISERVER-12815.  That is not the correct fix for the issue
@pamval, @kurtwalker, review it please
> [SP-2394] - Backport of BISERVER-12815 - Manage Data Sources: User can import an .xmi using "Import Analysis" (6.0 Suite)

- src/org/pentaho/platform/dataaccess/datasource/wizard/public/kettlethin_native.xul
Same xul changes as in kettle's dbdialog.
pentaho-data-refinery: https://github.com/pentaho/pentaho-data-refinery/pull/26
pentaho-commons-database: https://github.com/pentaho/pentaho-commons-database/pull/93
@mkambol
> [BACKLOG-7483] Add the field "webapp name" for Pentaho Data Service database type (DSW)

- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/CsvDatasourceServiceImpl.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ModelerService.java
- test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ModelerServiceIT.java
- Generating domain of csv datasource using CsvDatasourceImportStrategy, that binds column id's (column names on database level, that have some restrictions on chars in their name) with friendly column names (user-provided names, containing any chars)
> [BISERVER-13026] Imported CSV Data Source with Hyphen Character Does Not Display Correctly

- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/CsvDatasourceServiceImpl.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ModelerService.java
- test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ModelerServiceIT.java
- Generating domain of csv datasource using CsvDatasourceImportStrategy, that binds column id's (column names on database level, that have some restrictions on chars in their name) with friendly column names (user-provided names, containing any chars)
> [SP-2675] Backport of BISERVER-13026 - Imported CSV Data Source with Hyphen Character Does Not Display Correctly (6.1 Suite)

- src/org/pentaho/platform/dataaccess/datasource/wizard/service/SqlQueriesNotSupportedException.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImpl.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages.properties
- test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java
- Before executing SQL, checking whether sql queries can be executed via a given connection.
If connection is not allowed, throw SqlQueriesNotSupportedException with an exact message, that should be handled in the caller-methods.
- Removed some duplicated logging
> [BISERVER-13225] Unable to use 'SQL Query' source type with Data Service in Data Source Wizard

- src/org/pentaho/platform/dataaccess/datasource/wizard/service/SqlQueriesNotSupportedException.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImpl.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages.properties
- test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java
- Before executing SQL, checking whether sql queries can be executed via a given connection.
If connection is not allowed, throw SqlQueriesNotSupportedException with an exact message, that should be handled in the caller-methods.
- Removed some duplicated logging
> [SP-2689] Backport of BISERVER-13225 - Unable to use 'SQL Query' source type with Data Service in Data Source Wizard (6.1 Suite)

- src/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel_de.properties
@mchen-len-son , could you please merge this PR?
> [BISERVER-12726] l10n: "Next >" button caption is translatd incorrectly onto the German language

- src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages_de.properties
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages_fr.properties
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages_ja.properties
"Test Connection" dialog was fixed
> SP-2804  Backport of BISERVER-12964 - Localization - Test Connection dialog window isn't fully translated (Japanese and French) (6.1 Suite)

- ivy.xml
@pentaho/rogueone Upgrade to commons-fileupload-1.3.2. Please review.
> [BACKLOG-11322] Resolve Security Vulnerabilities around Apache Common File Upload

- src/org/pentaho/platform/dataaccess/datasource/ui/service/MetadataUIDatasourceService.java
- regression is fixed - metadata data sources now look consistent with data sources of other types on ui, without xmi suffix
This is a backport of #813
> [BISERVER-13273] Creation of duplicate datasource in PUC

- src/org/pentaho/platform/dataaccess/datasource/ui/service/MetadataUIDatasourceService.java
- regression is fixed - metadata data sources now look consistent with data sources of other types on ui, without xmi suffix
This is a backport of #813
> [BISERVER-13273] - Creation of duplicate datasource in PUC

- .classpath
- test-src/ESAPI.properties
Removing legacy ESAPI encoder from projects and replacing it by org.owasp.encoder
> PDI-15515- Removing legacy ESAPI encoder

- src/org/pentaho/platform/dataaccess/datasource/ui/importing/AnalysisImportDialogController.java
- src/org/pentaho/platform/dataaccess/datasource/ui/importing/AnalysisImportDialogModel.java
- src/org/pentaho/platform/dataaccess/datasource/utils/DataSourceInfoUtil.java
- src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DatasourceResource.java
- test-src/org/pentaho/platform/dataaccess/datasource/ui/importing/AnalysisImportDialogControllerTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/ui/importing/AnalysisImportDialogModelTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/utils/DataSourceInfoUtilTest.java
- test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DatasourceResourceTest.java
@pamval , @mbatchelor , @e-cuellar , @pentaho-nbaker  please review.
This PR is related to [PR in pentaho-platform](https://github.com/pentaho/pentaho-platform/pull/3286).
[jira issue](http://jira.pentaho.com/browse/BISERVER-13375), [previous PR](https://github.com/pentaho/pentaho-platform/pull/3270)
This PR needs resolve ENGOPS issue http://jira.pentaho.com/browse/ENGOPS-2643.
Don't merge this PR until the issue is closed.
This PR has "Still Broken Tests" message. This tests are not related to my changes. I don't see quick fix of them.
This PR contains following changes:
1. [DataSourceInfoUtil](https://github.com/pentaho/data-access/compare/master...VadimPolynkov:BISERVER-13375?expand=1#diff-e0ef69a5d7659ee402ff424b26e54ff2R26) class is added for custom escape and unescape quotes. In …
> [BISERVER-13375] Fixed addition parameters with specific characters

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java
- core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplTest.java
reverting changes for http://jira.pentaho.com/browse/BISERVER-13407 due to http://jira.pentaho.com/browse/BACKLOG-13455
http://jira.pentaho.com/browse/BACKLOG-13429
> [REVERT]:BISERVER-13407 ValidationQuery and Pooling options not sent to DB when datasource is defined in Manage DataSources Perspective

- core/pom.xml
- pom.xml
Removing legacy esapi encoder from the projects and replacing it by org.owasp.encoder
> [PDI-15515] - Removing legacy esapi encoder from the projects

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/ui/service/JdbcDatasourceService.java
name while preparing the url for deleting the datasource. The
dsInfo.getName() has been changed to escape the html characters.
> [BACKLOG-16051] Using the dsInfo.getId() which returns the non-escaped

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionService.java
- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java
- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizer.java
- core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplTest.java
@pentaho/rogueone Please review
Needed to make this change because other code areas were referencing the ConnectionServiceImpl instead of ConnectionService and querying for data connections with unsanitized parameters.
> [BACKLOG-16058] Changes UtilHtmlSanitizer function params and moves name sanitization from ConnectionService to ConnectionServiceImpl

- pom.xml
Upgrading jackrabbit version to 2.14.2
Refer to BACKLOG-17562 and PPP-3714 for details.
Related PRs being opened to upgrade other projects that depend on jackrabbit.
@pentaho/rogueone @pentaho/rebelalliance
pentaho-platform: https://github.com/pentaho/pentaho-platform/pull/3708
pentaho-kettle: https://github.com/pentaho/pentaho-kettle/pull/4174
pdi-ee-plugin: https://github.com/pentaho/pdi-ee-plugin/pull/340
> BACKLOG-17562: Upgrade data-access jackrabbit version to 2.14.2

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css
> [BISERVER-10582]-Database Connection Options List gets cut off when you have more than 5 parameters

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css
> [SP-3708][BISERVER-10582]-Database Connection Options List gets cut off when you have more than 5 parameters

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardService.java
- core/src/main/java/org/pentaho/platform/dataaccess/datasource/ui/importing/MetadataImportDialogController.java
Reverts pentaho/data-access#943 due to regression found. See BACKLOG-19112.
> Revert "[BISERVER-13338] - Data source domain object mutation while re-parsing"

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css
> [BISERVER-13755]-l10n - overlapping text on the Data Source Wizard dialogue

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java
- core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtilsTest.java
Related to https://github.com/pentaho/pentaho-metadata/pull/172/files
> [ANALYZER-3559]-When filtering the date field (format YYYY-MM-DD HH:MM:SS.0) it shows "The report has no data"

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java
- core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtilsTest.java
Reverts pentaho/data-access#955
> Revert "[ANALYZER-3559]-When filtering the date field (format YYYY-MM-DD HH:MM:SS.0) it shows "The report has no data""

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/MultitableDatasourceService.java
- fix for using the correct connection name
> [BACKLOG-21831] - Do not see streaming dataservices when creating a pentaho datasource

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/models/DatasourceModel.java
- core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/models/DatasourceModelTest.java
- core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java
- RegExp was modified in order to accept all alphanumeric unicode characters. Since GWT's RegExp is not supporting unicode flag on Java side (and pattern with unicode character class) the modified method is not working on the Java side, but works as expected on the JS side. That's why generateTableName() was mocked in tests and testGenerateTablename() method was removed.
- checkstyle fixes
> [PPP-4022] Japanese character in the data source name causes data inconsistency and an errors to occur

- core/src/test/resources/repository-test-override.spring-ext.xml
- core/src/test/resources/repository-test-security.spring.xml
- core/src/test/resources/repository.spring-ext.xml
- core/src/test/resources/solutionACL/system/repository-test-override.spring.xml
Reverts pentaho/data-access#959
- Reverted as per the decisions made ( and captured ) at https://jira.pentaho.com/browse/PPP-3876?focusedCommentId=336291#comment-336291
Part of a bulk-revert, comprised of the PR list captured at https://jira.pentaho.com/browse/PPP-3876?focusedCommentId=321593#comment-321593:
@pentaho/rogueone @pamval @dkincade @mbatchelor @mdamour1976 @graimundo 
~Please **hold off merging** until we have triggered a "Revert PR" for all PRs outlined in https://jira.pentaho.com/browse/PPP-3876?focusedCommentId=321593#comment-321593~ ✅ 
* https://github.com/pentaho/pentaho-engineering-samples/pull/61
* https://github.com/pentaho/marketplace/pull/147
* https://github.com/pentaho/data-access/pull/999
* https://github.com/pentaho/pentaho-kettle/pull/5176
* …
> Revert "[PPP-3876]-Use of vulnerable component spring-security-core 4.1.9 cve-2017-4995"

- core/pom.xml
@mbatchelor @pamval @pentaho-lmartins
> [BISERVER-13960] - data-access POM has typo in wadl output directory

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImpl.java
Fixes regression in `DSWDatasourceServiceImpl` due to:
> Axis2 does not work when using Java 8 features in the implementation class, because axis somehow has a problem analyzing that bytecode.
> 
> As a workaround, removing Java 8 features (e.g. streams) in the skeleton implementation solved it in my case. You can use those features anywhere except in the web service implementation class (when using Axis2).
Reverts some work in #1019 and rewrites the code so no streams are used.
@pedrofvteixeira @ricardosilva88 @graimundo
> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

- pom.xml
* [PPP-4266] Removed the version and reference from the top-level pom file, kept reference in the core/pom.xml so it will pull from the maven-parent-poms project for the updated version.
This is a series of PRs, please see pentaho/maven-parent-poms#83
> [PPP-4266] Use of Vulnerable Component commons-fileupload CVE-2016-1000031

- pom.xml
This is a series of PRs, please see: https://github.com/pentaho/maven-parent-poms/pull/85
> [SP-4828] - Backport of PPP-4266 - Use of Vulnerable Component: commons-fileupload-1.3.2.jar (CVE-2016-1000031 | sonatype-2014-01730) (7.1 Suite)

- pom.xml
This is a series of PRs, please see: https://github.com/pentaho/maven-parent-poms/pull/86
> [SP-4827] - Backport of PPP-4266 - Use of Vulnerable Component: commons-fileupload-1.3.2.jar (CVE-2016-1000031 | sonatype-2014-01730) (7.1 Suite)

- pom.xml
Removal of the Apache Derby version in favor of retrieving a unified version from the Maven parent POM. At the time of this PR, the latest version of Apache Derby is 10.15.1.3. Other PRs related to this one are listed below:
https://github.com/pentaho/maven-parent-poms/pull/122
https://github.com/pentaho/pentaho-platform/pull/4399
https://github.com/pentaho/pentaho-kettle/pull/6402
https://github.com/pentaho/pentaho-reporting/pull/1256
https://github.com/pentaho/data-access/pull/1053
> [BACKLOG-28357] Updates derby version, retrieves from parent POM

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataTempFilesListBundleDto.java
- core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataTempFilesListDto.java
- core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataTempFilesListDtoTest.java
Localization files are imported and saved with a unique ".tmp" name.
The logic to determine what locale a message file is is based on the
file name, and the .tmp name was screwing up the locale determination.
The existing code attempted to store both the "originalFileName"
and the tempFileName, but was setting the values incorrectly.
This change sets the original and tempname correctly, and
stores both in the JSON constructed list of locale bundles.
https://jira.pentaho.com/browse/BISERVER-14142
> [BISERVER-14142] Import Metadata-Pen Server fails to import localization

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataResource.java
[TEST] Adding test commit to force recompilation of Metadata Resource class for BISERVER-14281
@pentaho-lmartins
> BISERVER-14281 - Unable to export metadata data sources

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css
Database options box is now scrollable.  The height should only apply to the most immediate vbox and not all the child vboxes
> [BACKLOG-38099] - IAM credentials for redshift it PUC

- core/pom.xml
- pom.xml
This is part of a series of PRs. See https://github.com/pentaho/maven-parent-poms/pull/170 for details.
**Don't merge before the PR above.**
Reorganizing exclusions and transitive dependencies of `pentaho-metadata` and `xstream`.
> [PPP-4448] Use of Vulnerable Component - XStream 1.4.10

- core/pom.xml
- pom.xml
Replaces #1074. Don't need `jackrabbit-core`, it's a transitive of `pentaho-platform-repository`.
**Do not merge before https://github.com/pentaho/maven-parent-poms/pull/178!**
@ssamora @RPAraujo
> [PPP-4447] Use of vulnerable component - Tika Core 1.1x

- core/pom.xml
- pom.xml
@pentaho/tatooine @pentaho-lmartins @ssamora 
* [PDI-17775] Cleaning up version references to old commons-vfs2, unifying under maven parent pom.  Removing unused, declared dependency reference.
This PR is a part of a series of PR to upgrade commons-vfs2 and fix VFS issues with HTTP:
- https://github.com/pentaho/apache-vfs-browser/pull/60
- https://github.com/pentaho/big-data-plugin/pull/1929
- https://github.com/webdetails/cpk/pull/85
- https://github.com/pentaho/data-access/pull/1083
- https://github.com/pentaho/maven-parent-poms/pull/185
- https://github.com/pentaho/mondrian/pull/1177
- https://github.com/pentaho/pdi-jms-plugin/pull/73
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/102
- https://github.com/pentaho/pdi-plugins-ee/pull/139
- …
> [PDI-17775] Process Files step no longer supports HTTP scheme

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/modeler.xul
On certain zoom levels (> 200%) / screen sizes, the dialog content wouldn't occupy all the area available in the dialog container, resulting in a big white gap below the dialog action buttons.
> Address BACKLOG-36864: Fix dialog scroll behaviour while zoomed

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/dataaccess-databasedialog.xul
@pentaho/wcag , Please review
This PR is part of https://github.com/pentaho/pentaho-commons-database/pull/242
> [BACKLOG-38287] [Database Connection] -- The parameters section for pooling tab are not visible

- core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardServiceTest.java
Removing Tika dependency as it was a transative dependency that, now, does not exist.
> [CLEANUP] Fix DataSourceWizardServiceTest.java

- core/pom.xml
- core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/UploadFileDebugServlet.java
- core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/FileUploadServiceTest.java
[BACKLOG-41287]-Upgrading data-access from Java EE to Jakarta EE to be compatiable with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41287]-Upgrading data-access from Java EE to Jakarta EE to be compatiable with Tomcat-10.X

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
- core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java
Relates to SME-294 and https://github.com/pentaho/semantic-model-editor/pull/341
Add conditions with new property in mondrianCatalogs created by Semantic Model Editor to ensure SME models don't show up in the Manage Datasources menu.
> [SME-294] fix: Ensure SME models don't show as Analysis datasources 

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
- core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java
Cherry picked from commit https://github.com/pentaho/data-access/commit/2a1f19e79fb15913cac65d2f906f3267dd341b11
> [SP-6665] Backport of SME-294 - fix: Ensure SME models don't show as Analysis datasources

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
[SP-6689]-Backport of PPP-4862 - Use Pentaho-kettle's XMLParserFactoryProducer in Data-acccess (10.2 Suite)
[SP-6689]: https://hv-eng.atlassian.net/browse/SP-6689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SP-6689]-Backport of PPP-4862 - Use Pentaho-kettle's XMLParserFactoryProducer in Data-acccess (10.2 Suite)

- core/src/main/java/org/pentaho/platform/dataaccess/security/policy/rolebased/actions/DatasourceManageAction.java
This pull request introduces a new method `getLocalizedDescription` to the `DatasourceManageAction` class in the `core/src/main/java/org/pentaho/platform/dataaccess/security/policy/rolebased/actions/DatasourceManageAction.java` file. This method provides a localized description for the action, enhancing the class's support for internationalization.
Key change:
* Added the `getLocalizedDescription` method to return a localized description string based on the given locale. This complements the existing `getLocalizedDisplayName` method by providing additional context for the action.
should be merged after https://github.com/pentaho/pentaho-platform/pull/5911
@pentaho/millenniumfalcon please review
> feat: add description property to authorization actions [PPUC-64]

- core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
- core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardService.java
`getModrianSchemaFiles` was renamed to `getMondrianSchemaFiles` in https://github.com/pentaho/pentaho-platform/pull/5908. Fixing name in accordance.
> fix: fix method name

- core/src/main/java/org/pentaho/platform/dataaccess/security/policy/rolebased/actions/DatasourceManageAction.java
- gives access to new equals/hashCode implementations required by changes to IAuthorizationAction
Part of PR set: https://github.com/pentaho/pentaho-platform/pull/5974
> feat: change DatasourceManageAction to use AbstractAuthorizationAction
