test-src/org/pentaho/platform/dataaccess/datasource/DataSourcePublishACLTest.java, test-src/solutionACL/system/repository-test-override.spring.xml
now every project has it's own repo path
=> [TEST] - fix test

src/org/pentaho/platform/dataaccess/datasource/api/MetadataService.java, test-src/org/pentaho/platform/dataaccess/datasource/api/MetadataServiceTest.java
@CodeOnCoffee would you mind to review/merge please
There are  two commits in PR:
1) Unit test 
2) Fix
Resume: fixEncodedSlashParam method was replacing slashes therefore path to metadata file had not been found. Now method is not called at all.
=> BISERVER-12403

build.xml
=> [BACKLOG-2452] - Tentative fix for wadl generator target

src/org/pentaho/platform/dataaccess/datasource/wizard/GwtDatasourceEditorEntryPoint.java, src/org/pentaho/platform/dataaccess/datasource/wizard/controllers/WizardConnectionController.java
Cherry pick of https://github.com/diogofscmariano/data-access/commit/723c677204f0250106570797438c933f81132c0d
@pamval @kcruzada please review
=> [BACKLOG-3539] - Added cache buster to endpoint call

src/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel.xul
What was done:
1) added missed multiline attributes
=> BACKLOG-3378 -- German Layout Issues - Data Source Wizard

src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplTest.java
not clearing out the cached datasource, causing outdated datasource
info to be picked up elsewhere.
=> [BACKLOG-3549] Updating or deleting datasource connections was

src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionService.java
Goes with https://github.com/pentaho/pentaho-platform/pull/2346
=> BISERVER-12579 - Non-admin User Unable to add Data Source Connection

src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionService.java
@rmansoor 
Please review. Backport of https://github.com/pentaho/data-access/pull/637
Goes with https://github.com/pentaho/pentaho-platform/pull/2356
=> SP-1948 - Backport of BISERVER-12579 - Non-admin User Unable to add Data Source Connection (5.4 Suite)

src/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardService.java, test-src/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardServiceTest.java
@e-cuellar @scottyaslan @pentaho-nbaker 
please review and merge
=> [SP-2054] - removed unnecessary operation (slash escaping) from removeDsw()

src/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardService.java, test-src/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardServiceTest.java
@e-cuellar @scottyaslan  @pentaho-nbaker 
please review and merge
=> [BISERVER-12331] - removed unnecessary operation (slash escaping) from removeDsw()

ivy.xml
This pull request is one of pull-requests related to PDI-13231.
If you apply this request  you have to apply other pull-requests from this set:
https://github.com/pentaho/pentaho-metadata/pull/64
pentaho/pentaho-platform#2411
pentaho/pdi-agile-bi-plugin#38
@mbatchelor , @mdamour1976  please review.
=> [PDI-13231] - upgrade axis2 to 1.5

test-src/org/pentaho/platform/dataaccess/datasource/DataSourcePublishACLIT.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvModelServiceTest.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/csv/SerializeMultiTableServiceIT.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/csv/SerializeServiceIT.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/modeler/JoinMetadataIT.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/models/DatasourceModelTest.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/agile/CsvTransformGeneratorIT.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplIT.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DatasourceResourceIT.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ModelerServiceIT.java
@dkincade 
These changes are already in master. This PR is a cherry-pick into the 6.0 branch.
=> [BACKLOG-5383] - Classify Unit Test as Integration Tests

test-res/solution1/etc/mondrian/SampleData/schema.xml
@pentaho-nbaker, @rmansoor, @pamval, review it please.
I got a notification about failed tests (I'm not a culprit, it has been failing for 10 days already :smile:). This commit fixes it by putting absent file into the folder.
=> [TEST] - Fix failed test

src/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java, src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages.properties, test-src/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java
@rmansoor @lucboudreau 
Please review.
=> BISERVER-12815 - Manage Data Sources: User can import an .xmi using 'Import Analysis'

src/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
Backport of https://github.com/pentaho/data-access/pull/695
@rmansoor @pamval 
Please review.
=> Additional pr on SP-2394 - Backport of BISERVER-12815 - Manage Data Sources: User can import an .xmi using 'Import Analysis' (6.0 Suite)

test-src/org/pentaho/platform/dataaccess/datasource/DataSourcePublishIT.java
=> BACKLOG-7122 data-access - Integration test DataSourcePublishIT fails

src/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java, src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages.properties, test-src/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DatasourceResourceIT.java
@mdamour1976, @rmansoo, @e-cuellar, @pentaho-nbaker would you mind of reviewing/merging?
Here is platform's part: https://github.com/pentaho/pentaho-platform/pull/2929
=> [Biserver-12815] - Manage Data Sources: User can import an .xmi using "Import Analysis"

test-src/org/pentaho/platform/dataaccess/datasource/DataSourcePublishIT.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtilsTest.java
=> [TEST] Backporting changes for fixing tests in 6.1

src/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java, test-src/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceXxeAttackTest.java
- Adding IS_REPLACING_ENTITY_REFERENCES property, before parsing
@rmansoor, @mchen-len-son, review it please
=> [PPP-3506] XXE Security Vulnerability in xml parsers

src/org/pentaho/platform/dataaccess/metadata/model/Operator.java, src/org/pentaho/platform/dataaccess/metadata/model/impl/Condition.java, test-src/org/pentaho/platform/dataaccess/ConditionTest.java, test-src/org/pentaho/platform/dataaccess/OperatorTest.java
- Refactored Condition.java only call the getters instead of the having the attributes being called directly (useful for unit testing mocking )
=> [TEST] Added unit tests for Condition and Operator classes

src/org/pentaho/platform/dataaccess/metadata/service/MetadataService.java, src/org/pentaho/platform/dataaccess/metadata/service/MetadataServiceUtil.java, test-src/org/pentaho/platform/dataaccess/metadata/service/MetadataServiceTest.java
- Refactored MetadataService.java and MetadataServiceUtil.java (useful for unit testing mocking )
=> [TEST] Added unit test for MetadataService class

src/org/pentaho/platform/dataaccess/metadata/model/impl/Condition.java, test-src/org/pentaho/platform/dataaccess/ConditionTest.java
- Refactored Condition.java
- Change Condition class code on method getCondition, to stop passing
the value of the property "this.value" by reference
=> [TEST] Added more unit tests for Condition class

build.properties
Reverts pentaho/data-access#752
=> Revert "[PPP-3537] - Use of vulnerable component com.thoughtworks.xstream v1.…"

src/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel_de.properties
@mchen-len-son , @pamval , could you please merge this PR?
It's a backport of https://github.com/pentaho/data-access/pull/757
=> [SP-2753] Backport of BISERVER-12726 - l10n: Next

src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages_de.properties, src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages_fr.properties, src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages_ja.properties
"Test Connection" dialog was fixed
=> BISERVER-12964 Localization - Test Connection dialog window isn't fully translated (Japanese and French)

src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionService.java, src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizer.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizerTest.java
=> [PPP-3546] - Cross Site Scripting Vulnerability in Manage Data Sources

src/org/pentaho/platform/dataaccess/datasource/wizard/controllers/ConnectionController.java
@mchen-len-son, here is PR additional for client side.Thanks.
=> [PPP-3546] - client unescaption

src/org/pentaho/platform/dataaccess/datasource/wizard/controllers/ConnectionController.java, src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionService.java, src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizer.java, test-src/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizerTest.java
@mchen-len-son, @pamval, here is backport of   
https://github.com/pentaho/data-access/commit/a062318d9f8ecf3f28b63a2c2c471198a96104c1
https://github.com/pentaho/data-access/commit/e6d80c965f5a3bb763bc0848298151dbfd6f7f14
https://github.com/pentaho/data-access/commit/35364e10f63f3494ece9e52e222bfaf0c0b7bf6c
https://github.com/pentaho/data-access/commit/45e27c7d728f8dab0cc6cb58ed736e724a751904
to 6.1.Thanks.
=> [SP-2896] - Backport of PPP-3546 - Cross Site Scripting Vulnerability in Manage Data Sources (6.1 Suite)

src/org/pentaho/platform/dataaccess/datasource/ui/selectdialog/DatasourceSelectionDialogController.java, src/org/pentaho/platform/dataaccess/datasource/wizard/GwtDatasourceEditorEntryPoint.java
@pentaho/orlandocalisbon please review
=> [BACKLOG-11382] - Added cache buster for hasDataAccess calls

src/org/pentaho/platform/dataaccess/datasource/wizard/service/agile/StagingTransformGenerator.java
@mdamour1976 @bmorrise please review
=> [SPARKL-173] unnecessary table output initialization leaking connections

src/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages_ja.properties
[BACKLOG-7685] - L10N: Data Access related messages are not translated.
@tmorgner please review.
=> [BACKLOG-7685] - L10N: Data Access related messages are not translated.

src/org/pentaho/platform/dataaccess/datasource/api/MetadataService.java
- added xmi suffix forcing to import metadata method
=> [BISERVER-13273] Creation of duplicate datasource in PUC

src/org/pentaho/platform/dataaccess/datasource/api/MetadataService.java
- added xmi suffix forcing to import metadata method
=> [SP-2968][BISERVER-13273] Creation of duplicate datasource in PUC

ivy.xml
Reverts pentaho/data-access#807
Reverting for now since the platform upgrade still needs work
=> Revert "[PPP-3570] - Use of vulnerable component Apache Axis2 v.1.5.2 - CVE-2…"

ivy.xml
=> [PPP-3570] - revert

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplTest.java
-added processing for pooling ds case
-added unit test
=> [BISERVER-13407]-ValidationQuery and Pooling options not sent to DB when datasource is defined in Manage DataSources Perspective

ivy.xml
=> [SP-3086] Use of vulnerable component PDFBox v0.7.3 - CVE-2016-2175 (6.1 Suite)

core/pom.xml, pom.xml
only merge after https://github.com/pedrofvteixeira/pentaho-platform/tree/BACKLOG-12101 merge
=> [BACKLOG-12101] give classifier and GAV change to platform test jars

pom.xml
subject to merge of https://github.com/pentaho/pentaho-commons-json/pull/8
=> [ENGOPS-2639] distinguish org.json:json from org.pentaho:json

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/GwtDatasourceEditorEntryPoint.java
Here comes the other glasspane instance.
=> [PPP-3410]-Add an API to remove glasspane listeners

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/MetadataService.java, core/src/main/resources/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages.properties, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/MetadataServiceTest.java
@mbatchelor, @pamval, could you please take a look?
=> [BISERVER-13501] - Rest endpoints no longer validate the size of the upload for XMI

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplTest.java
Reverts pentaho/data-access#838
=> Revert "BISERVER-12605 - Testing a connection fails when we have same name for Named Datasource and JNDI datasource"

core/pom.xml, gwt/pom.xml, pom.xml
TO BE MERGED BY BUILDTEAM ONLY!   Pending upstream mavenization of reporting.
=> [BACKLOG-12334] GAV changes for reporting

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java
=> [BISERVER-13495]-Data access wizard doesn't release file handle if cancelled

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplTest.java
- added obtaining username before save new connection
=> [BISERVER-11727]-Oracle JNDI connection doesn't return any tables when creating a data source wizard connection

src/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java
=> [SP-3366][BISERVER-13495]-Data access wizard doesn't release file handle if cancelled

src/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java
=> [SP-3365][BISERVER-13495]-Data access wizard doesn't release file handle if cancelled

src/org/pentaho/platform/dataaccess/datasource/wizard/GwtDatasourceEditorEntryPoint.java
=> [SP-3339][PPP-3410]-Add an API to remove glasspane listeners

core/src/main/java/org/pentaho/platform/dataaccess/datasource/DatasourceInfo.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/DatasourceInfoTest.java
Created input sanitizer method to escape special symbols
=> [PPP-3685]-Cross-site scripting XSS vulnerability in DataSource name field

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/CsvDatasourceServiceImpl.java
- now error list complete instead of rewrite
=> [BACKLOG-15723]-CSV Data Source: Error Log is blank when the field length is less than the actual data coming in

src/org/pentaho/platform/dataaccess/datasource/ui/service/JdbcDatasourceService.java
=> [SP-3427] - Backport of PPP-3685 - Cross-site scripting XSS vulnerability in DataSource name field

src/org/pentaho/platform/dataaccess/datasource/ui/service/JdbcDatasourceService.java
=> [SP-3426] - Backport of PPP-3685 - Cross-site scripting XSS vulnerability in DataSource name field

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/ConnectionController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionService.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizer.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizerTest.java
@pentaho/rogueone Please review
=> [BACKLOG-16058] Sanitizes connection params for more endpoints to ensure proper addition/edit/display/deletion

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionService.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizer.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplTest.java
Reverts pentaho/data-access#882
=> Revert "[BACKLOG-16058] Changes UtilHtmlSanitizer function params and moves name sanitization from ConnectionService to ConnectionServiceImpl"

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionService.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/MultitableDatasourceService.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizer.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplTest.java
@pentaho/rogueone Please review
=> [BACKLOG-16058] Changes UtilHtmlSanitizer function params and moves name sanitization from ConnectionService to ConnectionServiceImpl

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/DatasourceService.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/DatasourceServiceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/MetadataServiceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/resources/JdbcDatasourceResourceTest.java
These are the changes made upon PR #829, only adding a unit tests and checkstyle fixes
=> [BISERVER-13192] REGRESSION: User with "Administer Security" permission can publish reports

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceXxeAttackTest.java
=> [BISERVER-13556]-Unable to Upload Mondrian Schemas using PUC

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceXxeAttackTest.java
Reverts pentaho/data-access#902
=> Revert "[BISERVER-13556]-Unable to Upload Mondrian Schemas using PUC"

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/MetadataService.java, core/src/main/resources/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages.properties, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/MetadataServiceTest.java
- endpoint fixed
- added unit test
=> [PMD-1068]-Able to Publish a model with no domain name

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/MetadataService.java, core/src/main/resources/org/pentaho/platform/dataaccess/datasource/wizard/service/messages/messages.properties, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/MetadataServiceTest.java
- endpoint fixed
- added unit test
=> [SP-3605][PMD-1068]-Able to Publish a model with no domain name

core/pom.xml, pom.xml
Reverts pentaho/data-access#913
=> Revert "[PPP-3735] - Use of vulnerable component httpclient-3.0.1.jar, common…"

core/pom.xml, core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisServiceXxeAttackTest.java, pom.xml
=> [SP-3652][BISERVER-13556]-Unable to Upload Mondrian Schemas using PUC

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardService.java
Merge metadata pull-request first https://github.com/pentaho/pentaho-metadata/pull/160
=> [BISERVER-10319]-Unable to move a DSW data source to another 5.X server.

core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardServiceTest.java
- tests repairing
@duarteteixeira, could you please take a look?
=> [BISERVER-13338] - Data source domain object mutation while re-parsing

.gitignore, core/src/main/resources-filtered/org/pentaho/platform/dataaccess/datasource/wizard/public/modeler.properties, core/src/main/resources-filtered/org/pentaho/platform/dataaccess/datasource/wizard/public/modeler_de.properties, core/src/main/resources-filtered/org/pentaho/platform/dataaccess/datasource/wizard/public/modeler_en.properties, core/src/main/resources-filtered/org/pentaho/platform/dataaccess/datasource/wizard/public/modeler_fr.properties, core/src/main/resources-filtered/org/pentaho/platform/dataaccess/datasource/wizard/public/modeler_ja.properties
@pentaho/millenniumfalcon @pentaho/2-1b please review
=> [BACKLOG-19262] Updated direct references to mindtouch links

core/src/it/java/org/pentaho/platform/dataaccess/datasource/DataSourcePublishIT.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/DatasourceWebServicesSecurityTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/CsvDatasourceServiceImplTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DataAccessServiceTestBase.java, core/src/test/resources/jackrabbit-test-repo.xml
=> [CLEANUP] - applay checkstyle, fix broken tests, fix the code to null

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardService.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/resources/DataSourceWizardResource.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataResource.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataTempFilesListDto.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataResourceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataTempFilesListDtoTest.java
@mchen-len-son Could you please take a look?
=> [SP-3717][BACKLOG-19051] - Unable to Import of Analysis Model from xmi file in IE11

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css
=> [SP-3915][BISERVER-13755]-l10n - overlapping text on the Data Source Wizard dialogue

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css
=> [SP-3914][BISERVER-13755]-l10n - overlapping text on the Data Source Wizard dialogue

gwt/pom.xml, pom.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-1757] version name consolidation

core/pom.xml, gwt/pom.xml, pom.xml
Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/649
=> [BACKLOG-20163] Update downstreams

pom.xml
=> [CLEANUP] fix reporting classic-core version prop

core/pom.xml, gwt/pom.xml, pom.xml
@pentaho/2-1b 
Depends on https://github.com/pentaho/pentaho-commons-xul/pull/143
=> [BACKLOG-20423] Update downstreams

core/pom.xml, gwt/pom.xml, pom.xml
@pentaho/2-1b gav change
for pentaho/pentaho-metadata/pull/186
=> [BACKLOG-13306] GAV change

pom.xml
@pentaho/2-1b gav change
for pentaho/pentaho-actionsequence-dom/pull/16
=> [BACKLOG-12713] GAV change

assemblies/data-access-plugin/pom.xml, core/pom.xml, gwt/pom.xml, pom.xml
@pentaho/x-wing 
Depends on https://github.com/pentaho/pentaho-commons-database/pull/149
=> [BACKLOG-20414] pentaho-commons-database downstream update

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/models/DatasourceModel.java
Reverts pentaho/data-access#1003
=> Revert "[BACKLOG-22645] - Error appears during creation new data source in Fi…"

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/models/DatasourceModel.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/models/DatasourceModelTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java
=> [SP-4257] Backport of PPP-4022 - Japanese character in the data source name causes data inconsistency and an errors to occur (8.0 Suite)

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/models/DatasourceModel.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/models/DatasourceModelTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java
=> [SP-4256] Backport of PPP-4022 - Japanese character in the data source name causes data inconsistency and an errors to occur (7.1 Suite)

core/pom.xml, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImpl.java, pom.xml
This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
=> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/MessageHandler.java
@pentaho/millenniumfalcon please review
=> [BACKLOG-17305] Removed references to pen.require and pen.define

pom.xml
This is a series of PRs, see https://github.com/pentaho/maven-parent-poms/pull/86
=> [SP-4827] - Backport of PPP-4266 - Use of Vulnerable Component: commons-fileupload-1.3.2.jar (CVE-2016-1000031 | sonatype-2014-01730) (7.1 Suite)

core/pom.xml, pom.xml
=> [BACKLOG-27575] Remove Felix Main dependency

pom.xml
Reverts pentaho/data-access#1053
=> Revert "[BACKLOG-28357] Updates derby version, retrieves from parent POM"

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataResource.java
=> [BISERVER-14281] - Unable to export metadata data sources

assemblies/data-access-plugin/src/main/resources/plugin.xml, assemblies/data-access-plugin/src/main/resources/settings.xml, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DatasourceServiceManagerGwtImpl.java, gwt/src/main/resources/org/pentaho/platform/dataaccess/datasource/DatasourceEditor.gwt.xml, gwt/src/main/resources/org/pentaho/platform/dataaccess/datasource/DatasourceEditorDebug.gwt.xml, gwt/src/main/resources/org/pentaho/platform/dataaccess/datasource/DatasourceEditorModule.gwt.xml
@pentaho/millenniumfalcon can you please review and merge
=> [BACKLOG-31894] - [MARKETO] CSFR - /data-access/api/datasource/analysis

gwt/src/main/resources/org/pentaho/platform/dataaccess/datasource/DatasourceEditor.gwt.xml, gwt/src/main/resources/org/pentaho/platform/dataaccess/datasource/DatasourceEditorDebug.gwt.xml, gwt/src/main/resources/org/pentaho/platform/dataaccess/datasource/DatasourceEditorModule.gwt.xml
@pentaho/millenniumfalcon review&merge pls
=> [CLEANUP] - Remove unused inherit

assemblies/data-access-plugin/src/main/resources/plugin.xml, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/ConnectionController.java
@pentaho/millenniumfalcon please review
=> [BACKLOG-31895] CSFR - /data-access/api/connection/add

assemblies/data-access-plugin/src/main/resources/plugin.xml, core/src/main/java/org/pentaho/platform/dataaccess/datasource/ui/importing/AnalysisImportDialogController.java
@pentaho/millenniumfalcon please review
=> [BACKLOG-31893] - [MARKETO] CSRF - /data-access/api/mondrian

core/pom.xml, pom.xml
This reverts commit 1158139a1b93009734b3bcd5a91c5e8b2c2649ec, reversing
changes made to 224589b36faf656cff5a4fc351e1d20cd8513d77.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …
=> Revert "Merge pull request #1090 from gryphendowre/SP-5370"

core/src/main/java/org/pentaho/platform/dataaccess/datasource/utils/Base64PasswordUtils.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/ConnectionController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/WizardConnectionController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizer.java
=> [BISERVER-14396] - Manage Datasources Perspective transmits password in clear text using checkParams API

core/src/main/java/org/pentaho/platform/dataaccess/datasource/utils/Base64PasswordUtils.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/ConnectionController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/WizardConnectionController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizer.java
=> [SP-5895] - Backport of BISERVER-14396 - Manage Datasources Perspective transmits password in clear text using checkParams API (9.1 Suite)

core/src/main/java/org/pentaho/platform/dataaccess/datasource/utils/Base64PasswordUtils.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/ConnectionController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/WizardConnectionController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/UtilHtmlSanitizer.java
=> [SP-5894] - Backport of BISERVER-14396 - Manage Datasources Perspective transmits password in clear text using checkParams API (8.3 Suite)

core/pom.xml, core/src/test/resources/repository-test-override.spring-ext.xml, core/src/test/resources/repository-test-security.spring.xml, core/src/test/resources/repository.spring-ext.xml, core/src/test/resources/solutionACL/system/importExport.xml, core/src/test/resources/solutionACL/system/pentahoObjects.spring.xml, core/src/test/resources/solutionACL/system/repository-test-override.spring.xml
config file updates in test resources.
=> [TEST] Fix failing IT test; missing dependencies and missed spring

assemblies/data-access-plugin/pom.xml, assemblies/data-access-plugin/src/main/resources/plugin.spring.xml, assemblies/data-access-plugin/src/main/resources/plugin.xml, assemblies/data-access-plugin/src/main/resources/settings.xml, pom.xml
Please, review:
@graimundo
/cc @bennychow if you want to review, be my guest!
/cc @jcarneirohv
Depends on pentaho/security-web#4.
=> [BACKLOG-35000] CSRF Refactor

core/src/main/java/org/pentaho/platform/dataaccess/datasource/ui/importing/AnalysisImportDialogController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/UploadFileEntryPoint.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/AnalysisDatasourceServiceGwtImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DatasourceServiceManagerGwtImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/MetadataDatasourceServiceGwtImpl.java
Depends on: https://github.com/pentaho/pentaho-platform/pull/4942.
See PR set: https://github.com/pentaho/security-web/pull/10.
@bennychow, @ddiroma please review and merge.
=> [BACKLOG-35298] CSRF - ImportDialog should specify the CSRF token as a form parameter

core/pom.xml, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtilsTest.java
@smmribeiro 
@andreramos89 
@renato-s
=> [BACKLOG-35399] - Update projects to include locale properties for integration test execution

core/pom.xml
@bcostahitachivantara @renato-s @andreramos89 @smaring
=> [SP-6106] Fix Unit Tests (8.3 Suite)

assemblies/data-access-plugin/src/main/resources/plugin.spring.xml
Please see main PR: https://github.com/pentaho/maven-parent-poms/pull/336.
=> [BACKLOG-35003] Changed to use the new CSRF configuration class

assemblies/data-access-plugin/src/main/resources/settings.xml, core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardService.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/DatasourceService.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/MetadataService.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/DataSourceWizardServiceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/DatasourceServiceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/MetadataServiceTest.java
Optimizing the performance to load the datasource Ids in Manage Datasource
=> BACKLOG-35854 Optimizing the performance to load the datasource Ids in MDS

assemblies/data-access-plugin/src/main/resources/resources/web/Xmla.js
=> [BACKLOG-35904] CSRF - Protect the Request Parameters authentication mechanism

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java, core/src/main/resources/org/pentaho/platform/dataaccess/metadata/messages/messages.properties
=> [PPP-4762] - Arbitrary File Read from Server's File System injecting traversal characters

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java, core/src/main/resources/org/pentaho/platform/dataaccess/metadata/messages/messages.properties
@smmribeiro 
@andreramos89 
@renato-s
=> [SP-6196] - Backport of PPP-4762 - Arbitrary File Read from Server's File System injecting traversal characters (9.3 Suite)

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
d87eaef92c527b1f8606e654fed59f4edc452ea5
=> [PPP-4797] Remove external entity retrieval for CVE-2022-43941

core/pom.xml, pom.xml
@bcostahitachivantara @renato-s @andreramos89
=> [PPP-4783] Vulnerable Component: nekohtml

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/CsvDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/InMemoryDSWDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/MultitableDatasourceService.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/LegacyDatasourceConverterTest.java
@smmribeiro 
@renato-s 
@bcostahitachivantara
=> [PPP-4704] - Vulnerable Component: xstream-1.4.17

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/CsvDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/InMemoryDSWDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/MultitableDatasourceService.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/LegacyDatasourceConverterTest.java
@renato-s 
@bcostahitachivantara 
@smmribeiro
=> [SP-6250] - Backport of PPP-4704 - Vulnerable Component: xstream-1.4.17 (9.3 Suite)

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/CsvDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/InMemoryDSWDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/MultitableDatasourceService.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/utils/LegacyDatasourceConverterTest.java
@smmribeiro 
@bcostahitachivantara 
@renato-s
=> [SP-6251] - Backport of PPP-4704 - Vulnerable Component: xstream-1.4.17 (9.4 Suite)

core/src/main/java/org/pentaho/platform/dataaccess/datasource/ui/admindialog/DatasourceAdminDialogController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/ui/importing/AnalysisImportDialogController.java
@pentaho/wcag , Please review
This PR is dependent on https://github.com/pentaho/pentaho-commons-xul/pull/218
=> [BACKLOG-36850] Focus Visible - Accessibility -  PUC Home Page – Manage Data Sources

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/MainWizardController.java
=> [BACKLOG-36852] WCAG changes for Data Source Wizard (Database Tables)

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/MainWizardController.java
@pentaho/wcag, Please review.
Fixing a regression from https://github.com/pentaho/data-access/pull/1180/files
=> [BACKLOG-36852] WCAG regression fix for Data Source Wizard (Database Tables)

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceAdminDialog.xul, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceManageDialog.xul, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceSelectionDialog.xul, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel.xul, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/modeler.xul
=> [BACKLOG-37005] Convert XUL Dialogs in to Alert Dialogs

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/sources/csv/StageDataStep.java
cherry-pick of https://github.com/pentaho/data-access/pull/1198  to master.
Dependent on https://github.com/pentaho/pentaho-commons-xul/pull/241
=> [BACKLOG-36722] Fixed a11y issues for CSV dialog

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/AbstractWizardStep.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel.xul
Depends on: 
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/929
- https://github.com/pentaho/pentaho-commons-xul/pull/244
@pentaho/wcag, please, review.
=> [BACKLOG-36863] Page Zoom (AA) - Data Source Wizard Dialog

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/modeler.xul
@pentaho/millenniumfalcon @pentaho/wcag please review
Depends on:
- https://github.com/pentaho/pentaho-commons-xul/pull/249
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/933
=> [BACKLOG-36864] Page Zoom (AA) - Data Source Model Editor Dialog

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel.xul
@pentaho/wcag , Please review
PR set:
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/935
- https://github.com/pentaho/pentaho-commons-xul/pull/250
=> [BACKLOG-36863] Page Zoom (AA) - Data Source Wizard Dialog - Landing Dialog

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/dataaccess-databasedialog.xul, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css
@pentaho/millenniumfalcon and @pentaho/wcag please review.
This PR needs to be merged with:
[https://github.com/pentaho/pentaho-commons-gwt-modules/pull/934](https://github.com/pentaho/pentaho-commons-gwt-modules/pull/934)
and
[https://github.com/pentaho/pentaho-commons-database/pull/231](https://github.com/pentaho/pentaho-commons-database/pull/231)
=> [BACKLOG-36862] - Page Zoom (AA) - Database Connection Dialog

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel.xul
@pentaho/wcag Please review
This PR is part of 
https://github.com/pentaho/pentaho-analyzer/pull/2447
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/939
=> [BACKLOG-37742] Page Zoom (AA) - Data Source Wizard Dialog-Database tables subsequent dialogs

core/src/main/java/org/pentaho/platform/dataaccess/datasource/ui/importing/AnalysisImportDialogController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceAdminDialog.xul, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/importDialog.xul
@pentaho/wcag Please Review
This PR is a part of 
https://github.com/pentaho/pentaho-commons-xul/pull/252
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/941
=> [BACKLOG-36861] - Page Zoom (AA) - Manage Data Source Dialog

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css
@pentaho/millenniumfalcon @pentaho/wcag please review
Depends on:
- https://github.com/pentaho/pentaho-commons-xul/pull/253
- https://github.com/pentaho/modeler/pull/385
=> [BACKLOG-36864] Page Zoom (AA) - Make Datasource Model Editor dialog table's icons zoomable

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/dataaccess-databasedialog.xul, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceEditorDialog.css
=> [BACKLOG-38108] In new data base connection window for Interactive report the other options for this connection are not visible

assemblies/data-access-plugin/pom.xml, assemblies/pom.xml, core/pom.xml, gwt/pom.xml, pom.xml
[CLEANUP] updated versions via release version merger
=> Merging master into wcag

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/controllers/WizardRelationalDatasourceController.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel.xul
@pentaho/wcag  , Please review for https://hv-eng.atlassian.net/browse/BACKLOG-37966
=> [BACKLOG-37966] Toolbar improvements in PUC

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/datasourceSelectionDialog.xul, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/public/main_wizard_panel.xul
@pentaho/wcag , Please Review.
Following XUL file is used for a toolbar which is used In PIR as well as PDD
=> [BACKLOG-37966] Toolbar improvements for PIR+PDD

core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/resources/JDBCDatasourceResourceTest.java
=> [PPP-4947] - When exporting a JDBC connection using API the password gets assigned a null value it cannot be reused anywhere else

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/csv/CsvUtils.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/CsvDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/InMemoryDSWDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/MultitableDatasourceService.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/MetadataDatasourceServiceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DSWDatasourceServiceImplTest.java
The DatabaseType.class was added to a few XStream (with allowed types) converters.
The one causing the error was in the class MultiTableDatasourceService.
@smmribeiro 
@renato-s 
@bcostahitachivantara
=> [BISERVER-14977] - Unable to Edit from DataSource Model Editor

pom.xml
=> [PPP-4936] - Vulnerable component upgrade guava version to guava-32.1.2

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/CsvDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/InMemoryDSWDatasourceServiceImpl.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/MultitableDatasourceService.java
Adding Join Model Classes to XStream allowed classes. Issue found in automation tests.
@smmribeiro 
@bcostahitachivantara 
@renato-s
=> [BISERVER-14977] - Unable to Edit from DataSource Model Editor - Adding Join Model Classes to XStream allowed classes

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/AnalysisService.java
[PPP-4862]-Use Pentaho-kettle's XMLParserFactoryProducer in Data-acccess
[PPP-4862]: https://hv-eng.atlassian.net/browse/PPP-4862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPP-4862]-Use Pentaho-kettle's XMLParserFactoryProducer in Data-acccess

assemblies/data-access-plugin/src/main/resources/plugin.spring.xml, assemblies/data-access-plugin/src/main/resources/plugin.xml, assemblies/data-access-plugin/src/main/resources/resources/web/models-mql.js, core/src/main/java/org/pentaho/platform/dataaccess/metadata/model/impl/Model.java, core/src/main/java/org/pentaho/platform/dataaccess/metadata/model/impl/ModelInfo.java, core/src/main/java/org/pentaho/platform/dataaccess/metadata/service/MetadataService.java, core/src/test/java/org/pentaho/platform/dataaccess/metadata/service/MetadataServiceTest.java, pom.xml
=> [PPP-4174] Migrate axis2 web services to jax-rs and remove axis2

core/src/it/java/org/pentaho/platform/dataaccess/datasource/DataSourcePublishIT.java
[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x
[BACKLOG-41601]: https://hv-eng.atlassian.net/browse/BACKLOG-41601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x

core/src/main/java/org/pentaho/platform/dataaccess/metadata/service/MetadataService.java, core/src/test/java/org/pentaho/platform/dataaccess/metadata/service/MetadataServiceTest.java
=> [PPP-4174] Ensure JSON data is returned; DatasourceEditor gwt code was

core/src/main/java/org/pentaho/platform/dataaccess/metadata/service/MetadataService.java, core/src/test/java/org/pentaho/platform/dataaccess/metadata/service/MetadataServiceTest.java
Reverts pentaho/data-access#1275
=> Revert "[PPP-4174] Ensure JSON data is returned; DatasourceEditor gwt code was"

core/src/main/java/org/pentaho/platform/dataaccess/metadata/model/IColumn.java, core/src/main/java/org/pentaho/platform/dataaccess/metadata/model/ICondition.java, core/src/main/java/org/pentaho/platform/dataaccess/metadata/model/impl/Category.java, core/src/main/java/org/pentaho/platform/dataaccess/metadata/model/impl/Column.java, core/src/main/java/org/pentaho/platform/dataaccess/metadata/model/impl/Condition.java, core/src/main/java/org/pentaho/platform/dataaccess/metadata/model/impl/ModelInfoComparator.java, core/src/main/java/org/pentaho/platform/dataaccess/metadata/model/impl/Query.java, core/src/test/java/org/pentaho/platform/dataaccess/ConditionTest.java, core/src/test/java/org/pentaho/platform/dataaccess/metadata/service/MetadataServiceTest.java
=> [PPP-4174] Use classes from data-access when processing responses from

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java
This PR needs to be merged with https://github.com/pentaho/pentaho-platform/pull/5798
@pentaho/tatooine_dev please review
=> fix: Invalid database connection is saved AND used despite "CANCEL"

core/src/main/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImpl.java
(cherry picked from commit de29915fe343a04c137572b3b92a3dc9c43ff57f)
@pentaho/tatooine_dev
=> fix: Invalid database connection is saved AND used despite "CANCEL" [SP-6724]

core/src/it/java/org/pentaho/platform/dataaccess/datasource/DataSourcePublishIT.java, core/src/it/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DatasourceResourceIT.java, pom.xml
[BACKLOG-41693]-Fix all the broken testcases in data-access
[BACKLOG-41693]: https://hv-eng.atlassian.net/browse/BACKLOG-41693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-41693]-Fix all the broken testcases in data-access

core/pom.xml, core/src/main/java/org/pentaho/platform/dataaccess/datasource/utils/Base64PasswordUtils.java, pom.xml
[BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version
[BACKLOG-43757]: https://hv-eng.atlassian.net/browse/BACKLOG-43757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version

core/pom.xml, core/src/it/java/org/pentaho/platform/dataaccess/datasource/wizard/service/agile/CsvTransformGeneratorIT.java, core/src/it/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplIT.java, core/src/it/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DatasourceResourceIT.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DataAccessServiceTestBase.java
Fixes:
- CsvTransformGeneratorIT.testCreateOrModifyTable_NullInput
- DatasourceResourceIT.testMetadataImportExport
- DatasourceResourceIT.testPublishDsw
=> [BACKLOG-43744] Fix Integration Tests errors

core/pom.xml, core/src/it/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/ConnectionServiceImplIT.java, core/src/it/java/org/pentaho/platform/dataaccess/datasource/wizard/service/impl/DatasourceResourceIT.java, core/src/test/resources/solutionACL/system/repository-test-override.spring.xml
=> [BACKLOG-43744] Fix Integration Tests

core/pom.xml, pom.xml
=> chore[PPP-5719]: move saxon version to pentaho parent pom

core/pom.xml
=> chore[PPP-5719]: upgrade Saxon dependency

core/pom.xml
Reverts pentaho/data-access#1325
=> Revert "chore[PPP-5719]: upgrade Saxon dependency"

core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/MetadataService.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/resources/DataSourceWizardResource.java, core/src/main/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataResource.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/resources/DataSourceWizardResourceTest.java, core/src/test/java/org/pentaho/platform/dataaccess/datasource/api/resources/MetadataResourceTest.java
[BACKLOG-45714]-Returning 400 Bad Request error while importing the data sources in PUC
[BACKLOG-45714]: https://hv-eng.atlassian.net/browse/BACKLOG-45714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-45714]-Returning 400 Bad Request error while importing the data sources in PUC

core/pom.xml
=> chore[PPP-5719]: add exclusion for xalan dependency in gwtmockito
